const wordCollections = {
    // --- ТЕМА 1: КТО Я / СЕМЬЯ ---
    "Кто я?": {
        simple: [
            { id: 1001, de: "ich", ru: "Я" },
            { id: 1002, de: "du", ru: "Ты" },
            { id: 1003, de: "der Name", ru: "Имя" },
            { id: 1004, de: "die Familie", ru: "Семья" },
            { id: 1005, de: "der Vater", ru: "Папа" },
            { id: 1006, de: "die Mutter", ru: "Мама" },
            { id: 1007, de: "der Bruder", ru: "Брат" },
            { id: 1008, de: "die Schwester", ru: "Сестра" },
            { id: 1009, de: "das Kind", ru: "Ребенок" },
            { id: 1010, de: "der Sohn", ru: "Сын" },
            { id: 1011, de: "die Tochter", ru: "Дочь" },
            { id: 1012, de: "der Mann", ru: "Мужчина / Муж" },
            { id: 1013, de: "die Frau", ru: "Женщина / Жена" },
            { id: 1014, de: "der Opa", ru: "Дедушка" },
            { id: 1015, de: "die Oma", ru: "Бабушка" },
            { id: 1016, de: "die Eltern", ru: "Родители" },
            { id: 1017, de: "die Geschwister", ru: "Братья и сестры" },
            { id: 1018, de: "das Baby", ru: "Младенец" },
            { id: 1019, de: "der Junge", ru: "Мальчик" },
            { id: 1020, de: "das Mädchen", ru: "Девочка" }
        ],
        hard: [
            { id: 1051, de: "verheiratet", ru: "Замужем / Женат" },
            { id: 1052, de: "ledig", ru: "Холост / Не замужем" },
            { id: 1053, de: "geschieden", ru: "Разведен(а)" },
            { id: 1054, de: "alt", ru: "Старый" },
            { id: 1055, de: "jung", ru: "Молодой" },
            { id: 1056, de: "groß", ru: "Большой / Высокий" },
            { id: 1057, de: "klein", ru: "Маленький" },
            { id: 1058, de: "die Person", ru: "Личность" },
            { id: 1059, de: "der Mensch", ru: "Человек" },
            { id: 1060, de: "das Alter", ru: "Возраст" },
            { id: 1061, de: "wohnen", ru: "Жить (где-то)" },
            { id: 1062, de: "leben", ru: "Жить (существовать)" },
            { id: 1063, de: "heißen", ru: "Называться" },
            { id: 1064, de: "kommen", ru: "Приходить / Приезжать" },
            { id: 1065, de: "sprechen", ru: "Говорить" },
            { id: 1066, de: "geboren", ru: "Рожденный" },
            { id: 1067, de: "der Geburtsort", ru: "Место рождения" },
            { id: 1068, de: "der Wohnort", ru: "Место жительства" },
            { id: 1069, de: "die Adresse", ru: "Адрес" },
            { id: 1070, de: "das Telefon", ru: "Телефон" }
        ]
    },

    // --- ТЕМА 2: ЦИФРЫ ---
    "Цифры": {
        simple: [
            { id: 2001, de: "null", ru: "0" },
            { id: 2002, de: "eins", ru: "1" },
            { id: 2003, de: "zwei", ru: "2" },
            { id: 2004, de: "drei", ru: "3" },
            { id: 2005, de: "vier", ru: "4" },
            { id: 2006, de: "fünf", ru: "5" },
            { id: 2007, de: "sechs", ru: "6" },
            { id: 2008, de: "sieben", ru: "7" },
            { id: 2009, de: "acht", ru: "8" },
            { id: 2010, de: "neun", ru: "9" },
            { id: 2011, de: "zehn", ru: "10" },
            { id: 2012, de: "elf", ru: "11" },
            { id: 2013, de: "zwölf", ru: "12" },
            { id: 2021, de: "dreizehn", ru: "13" },
            { id: 2022, de: "vierzehn", ru: "14" },
            { id: 2023, de: "fünfzehn", ru: "15" },
            { id: 2024, de: "sechzehn", ru: "16" },
            { id: 2025, de: "siebzehn", ru: "17" },
            { id: 2026, de: "achtzehn", ru: "18" },
            { id: 2027, de: "neunzehn", ru: "19" },
            { id: 2014, de: "zwanzig", ru: "20" },
            { id: 2015, de: "dreißig", ru: "30" },
            { id: 2016, de: "vierzig", ru: "40" },
            { id: 2017, de: "fünfzig", ru: "50" },
            { id: 2028, de: "sechzig", ru: "60" },
            { id: 2029, de: "siebzig", ru: "70" },
            { id: 2030, de: "achtzig", ru: "80" },
            { id: 2031, de: "neunzig", ru: "90" },
            { id: 2018, de: "hundert", ru: "100" },
            { id: 2019, de: "tausend", ru: "1000" },
            { id: 2020, de: "die Nummer", ru: "Номер" }
        ],
        hard: [
            { id: 2051, de: "erste", ru: "Первый" },
            { id: 2052, de: "zweite", ru: "Второй" },
            { id: 2053, de: "dritte", ru: "Третий" },
            { id: 2054, de: "letzte", ru: "Последний" },
            { id: 2055, de: "nächste", ru: "Следующий" },
            { id: 2056, de: "einmal", ru: "1 раз" },
            { id: 2057, de: "zweimal", ru: "2 раза" },
            { id: 2058, de: "die Hälfte", ru: "Половина (1/2)" },
            { id: 2059, de: "das Drittel", ru: "Треть (1/3)" },
            { id: 2060, de: "das Viertel", ru: "Четверть (1/4)" },
            { id: 2061, de: "beide", ru: "Оба" },
            { id: 2062, de: "wenig", ru: "Мало" },
            { id: 2063, de: "viel", ru: "Много" },
            { id: 2064, de: "mehr", ru: "Больше" },
            { id: 2065, de: "weniger", ru: "Меньше" },
            { id: 2066, de: "die Million", ru: "Миллион" },
            { id: 2067, de: "rechnen", ru: "Считать (вычислять)" },
            { id: 2068, de: "zählen", ru: "Считать (по порядку)" },
            { id: 2069, de: "das Ergebnis", ru: "Результат" },
            { id: 2070, de: "die Zahl", ru: "Число" }
        ]
    },

    // --- ТЕМА 3: ДОМ ---
    "Дом": {
        simple: [
            { id: 3001, de: "das Haus", ru: "Дом" },
            { id: 3002, de: "die Wohnung", ru: "Квартира" },
            { id: 3003, de: "das Zimmer", ru: "Комната" },
            { id: 3004, de: "die Küche", ru: "Кухня" },
            { id: 3005, de: "das Bad", ru: "Ванная" },
            { id: 3006, de: "das Fenster", ru: "Окно" },
            { id: 3007, de: "die Tür", ru: "Дверь" },
            { id: 3008, de: "der Tisch", ru: "Стол" },
            { id: 3009, de: "der Stuhl", ru: "Стул" },
            { id: 3010, de: "das Bett", ru: "Кровать" },
            { id: 3011, de: "der Schrank", ru: "Шкаф" },
            { id: 3012, de: "das Licht", ru: "Свет" },
            { id: 3013, de: "der Schlüssel", ru: "Ключ" },
            { id: 3014, de: "die Treppe", ru: "Лестница" },
            { id: 3015, de: "der Balkon", ru: "Балкон" },
            { id: 3016, de: "die Wand", ru: "Стена" },
            { id: 3017, de: "der Boden", ru: "Пол" },
            { id: 3018, de: "der Garten", ru: "Сад" },
            { id: 3019, de: "die Miete", ru: "Аренда" },
            { id: 3020, de: "nach Hause", ru: "Домой" }
        ],
        hard: [
            { id: 3051, de: "einziehen", ru: "Въезжать" },
            { id: 3052, de: "ausziehen", ru: "Выезжать" },
            { id: 3053, de: "renovieren", ru: "Ремонтировать" },
            { id: 3054, de: "möbliert", ru: "Меблированный" },
            { id: 3055, de: "der Stock", ru: "Этаж" },
            { id: 3056, de: "der Aufzug", ru: "Лифт" },
            { id: 3057, de: "die Nachbarn", ru: "Соседи" },
            { id: 3058, de: "die Heizung", ru: "Отопление" },
            { id: 3059, de: "das Gas", ru: "Газ" },
            { id: 3060, de: "der Strom", ru: "Электричество" },
            { id: 3061, de: "die Kosten", ru: "Расходы" },
            { id: 3062, de: "die Nebenkosten", ru: "Коммунальные" },
            { id: 3063, de: "sauber", ru: "Чистый" },
            { id: 3064, de: "грязный", ru: "Грязный" },
            { id: 3065, de: "hell", ru: "Светлый" },
            { id: 3066, de: "dunkel", ru: "Темный" },
            { id: 3067, de: "gemütlich", ru: "Уютный" },
            { id: 3068, de: "aufräumen", ru: "Убираться" },
            { id: 3069, de: "putzen", ru: "Чистить" },
            { id: 3070, de: "waschen", ru: "Стирать" }
        ]
    },

    // --- ТЕМА 4: ГОРОД / ТРАНСПОРТ ---
    "Город": {
        simple: [
            { id: 4001, de: "die Stadt", ru: "Город" },
            { id: 4002, de: "die Straße", ru: "Улица" },
            { id: 4003, de: "der Platz", ru: "Площадь / Место" },
            { id: 4004, de: "das Auto", ru: "Машина" },
            { id: 4005, de: "der Bus", ru: "Автобус" },
            { id: 4006, de: "der Zug", ru: "Поезд" },
            { id: 4007, de: "die Bahn", ru: "Ж/Д / Трамвай" },
            { id: 4008, de: "das Fahrrad", ru: "Велосипед" },
            { id: 4009, de: "das Flugzeug", ru: "Самолет" },
            { id: 4010, de: "das Schiff", ru: "Корабль" },
            { id: 4011, de: "der Bahnhof", ru: "Вокзал" },
            { id: 4012, de: "der Flughafen", ru: "Аэропорт" },
            { id: 4013, de: "die Haltestelle", ru: "Остановка" },
            { id: 4014, de: "das Ticket", ru: "Билет" },
            { id: 4015, de: "das Hotel", ru: "Отель" },
            { id: 4016, de: "das Restaurant", ru: "Ресторан" },
            { id: 4017, de: "das Café", ru: "Кафе" },
            { id: 4018, de: "die Bank", ru: "Банк" },
            { id: 4019, de: "die Post", ru: "Почта" },
            { id: 4020, de: "das Zentrum", ru: "Центр" }
        ],
        hard: [
            { id: 4051, de: "fahren", ru: "Ехать" },
            { id: 4052, de: "fliegen", ru: "Летать" },
            { id: 4053, de: "umsteigen", ru: "Пересаживаться" },
            { id: 4054, de: "aussteigen", ru: "Выходить (трансп.)" },
            { id: 4055, de: "einsteigen", ru: "Садиться (трансп.)" },
            { id: 4056, de: "abfahren", ru: "Отправляться" },
            { id: 4057, de: "ankommen", ru: "Прибывать" },
            { id: 4058, de: "die Verspätung", ru: "Опоздание" },
            { id: 4059, de: "der Fahrplan", ru: "Расписание" },
            { id: 4060, de: "das Gleis", ru: "Путь (ж/д)" },
            { id: 4061, de: "der Bahnsteig", ru: "Платформа" },
            { id: 4062, de: "die Ampel", ru: "Светофор" },
            { id: 4063, de: "die Ecke", ru: "Угол" },
            { id: 4064, de: "geradeaus", ru: "Прямо" },
            { id: 4065, de: "links", ru: "Налево" },
            { id: 4066, de: "rechts", ru: "Направо" },
            { id: 4067, de: "weit", ru: "Далеко" },
            { id: 4068, de: "nah", ru: "Близко" },
            { id: 4069, de: "zu Fuß", ru: "Пешком" },
            { id: 4070, de: "die Karte", ru: "Карта" }
        ]
    },

    // --- ТЕМА 5: ВРЕМЯ ---
    "Время": {
        simple: [
            { id: 5001, de: "die Zeit", ru: "Время" },
            { id: 5002, de: "das Jahr", ru: "Год" },
            { id: 5003, de: "der Monat", ru: "Месяц" },
            { id: 5004, de: "die Woche", ru: "Неделя" },
            { id: 5005, de: "der Tag", ru: "День" },
            { id: 5006, de: "die Stunde", ru: "Час" },
            { id: 5007, de: "die Minute", ru: "Минута" },
            { id: 5008, de: "die Sekunde", ru: "Секунда" },
            { id: 5009, de: "heute", ru: "Сегодня" },
            { id: 5010, de: "morgen", ru: "Завтра" },
            { id: 5011, de: "gestern", ru: "Вчера" },
            { id: 5012, de: "jetzt", ru: "Сейчас" },
            { id: 5013, de: "Montag", ru: "Понедельник" },
            { id: 5014, de: "Dienstag", ru: "Вторник" },
            { id: 5015, de: "Mittwoch", ru: "Среда" },
            { id: 5016, de: "Donnerstag", ru: "Четверг" },
            { id: 5017, de: "Freitag", ru: "Пятница" },
            { id: 5018, de: "Samstag", ru: "Суббота" },
            { id: 5019, de: "Sonntag", ru: "Воскресенье" },
            { id: 5020, de: "das Wochenende", ru: "Выходные" }
        ],
        hard: [
            { id: 5051, de: "früh", ru: "Рано" },
            { id: 5052, de: "spät", ru: "Поздно" },
            { id: 5053, de: "pünktlich", ru: "Пунктуально" },
            { id: 5054, de: "sofort", ru: "Немедленно" },
            { id: 5055, de: "manchmal", ru: "Иногда" },
            { id: 5056, de: "oft", ru: "Часто" },
            { id: 5057, de: "immer", ru: "Всегда" },
            { id: 5058, de: "nie", ru: "Никогда" },
            { id: 5059, de: "bald", ru: "Скоро" },
            { id: 5060, de: "damals", ru: "Тогда" },
            { id: 5061, de: "früher", ru: "Раньше" },
            { id: 5062, de: "später", ru: "Позже" },
            { id: 5063, de: "dauern", ru: "Длиться" },
            { id: 5064, de: "der Termin", ru: "Встреча (назнач.)" },
            { id: 5065, de: "die Uhrzeit", ru: "Время на часах" },
            { id: 5066, de: "viertel", ru: "Четверть" },
            { id: 5067, de: "halb", ru: "Половина" },
            { id: 5068, de: "vormittags", ru: "До обеда" },
            { id: 5069, de: "nachmittags", ru: "После обеда" },
            { id: 5070, de: "nachts", ru: "Ночью" }
        ]
    },

    // --- ТЕМА 6: РАБОТА ---
    "Работа": {
        simple: [
            { id: 6001, de: "die Arbeit", ru: "Работа" },
            { id: 6002, de: "der Job", ru: "Профессия / Работа" },
            { id: 6003, de: "der Chef", ru: "Начальник" },
            { id: 6004, de: "die Firma", ru: "Фирма" },
            { id: 6005, de: "das Büro", ru: "Офис" },
            { id: 6006, de: "der Kollege", ru: "Коллега" },
            { id: 6007, de: "die Schule", ru: "Школа" },
            { id: 6008, de: "der Lehrer", ru: "Учитель" },
            { id: 6009, de: "der Schüler", ru: "Ученик" },
            { id: 6010, de: "das Buch", ru: "Книга" },
            { id: 6011, de: "der Stift", ru: "Ручка / Карандаш" },
            { id: 6012, de: "das Papier", ru: "Бумага" },
            { id: 6013, de: "lernen", ru: "Учиться" },
            { id: 6014, de: "arbeiten", ru: "Работать" },
            { id: 6015, de: "lesen", ru: "Читать" },
            { id: 6016, de: "schreiben", ru: "Писать" },
            { id: 6017, de: "verstehen", ru: "Понимать" },
            { id: 6018, de: "fragen", ru: "Спрашивать" },
            { id: 6019, de: "antworten", ru: "Отвечать" },
            { id: 6020, de: "die Prüfung", ru: "Экзамен" }
        ],
        hard: [
            { id: 6051, de: "die Ausbildung", ru: "Обучение (проф.)" },
            { id: 6052, de: "das Studium", ru: "Учеба (ВУЗ)" },
            { id: 6053, de: "arbeitslos", ru: "Безработный" },
            { id: 6054, de: "der Beruf", ru: "Профессия" },
            { id: 6055, de: "verdienen", ru: "Зарабатывать" },
            { id: 6056, de: "das Gehalt", ru: "Зарплата" },
            { id: 6057, de: "kündigen", ru: "Увольняться" },
            { id: 6058, de: "der Vertrag", ru: "Договор" },
            { id: 6059, de: "die Pause", ru: "Перерыв" },
            { id: 6060, de: "der Erfolg", ru: "Успех" },
            { id: 6061, de: "schwer", ru: "Трудный" },
            { id: 6062, de: "leicht", ru: "Легкий" },
            { id: 6063, de: "fleißig", ru: "Старательный" },
            { id: 6064, de: "faul", ru: "Ленивый" },
            { id: 6065, de: "wichtig", ru: "Важный" },
            { id: 6066, de: "erklären", ru: "Объяснять" },
            { id: 6067, de: "wiederholen", ru: "Повторять" },
            { id: 6068, de: "üben", ru: "Упражняться" },
            { id: 6069, de: "die Hausaufgabe", ru: "Домашнее задание" },
            { id: 6070, de: "das Zeugnis", ru: "Аттестат / Свид-во" }
        ]
    },

    // --- ТЕМА 7: ПРИРОДА ---
    "Природа": {
        simple: [
            { id: 7001, de: "die Natur", ru: "Природа" },
            { id: 7002, de: "die Sonne", ru: "Солнце" },
            { id: 7003, de: "der Mond", ru: "Луна" },
            { id: 7004, de: "der Stern", ru: "Звезда" },
            { id: 7005, de: "der Himmel", ru: "Небо" },
            { id: 7006, de: "die Erde", ru: "Земля" },
            { id: 7007, de: "das Wasser", ru: "Вода" },
            { id: 7008, de: "das Meer", ru: "Море" },
            { id: 7009, de: "der See", ru: "Озеро" },
            { id: 7010, de: "der Fluss", ru: "Река" },
            { id: 7011, de: "der Wald", ru: "Лес" },
            { id: 7012, de: "der Baum", ru: "Дерево" },
            { id: 7013, de: "die Blume", ru: "Цветок" },
            { id: 7014, de: "das Wetter", ru: "Погода" },
            { id: 7015, de: "der Regen", ru: "Дождь" },
            { id: 7016, de: "der Schnee", ru: "Снег" },
            { id: 7017, de: "der Wind", ru: "Ветер" },
            { id: 7018, de: "warm", ru: "Тепло" },
            { id: 7019, de: "kalt", ru: "Холодно" },
            { id: 7020, de: "schön", ru: "Красиво" }
        ],
        hard: [
            { id: 7051, de: "die Luft", ru: "Воздух" },
            { id: 7052, de: "der Berg", ru: "Гора" },
            { id: 7053, de: "die Insel", ru: "Остров" },
            { id: 7054, de: "der Strand", ru: "Пляж" },
            { id: 7055, de: "die Umwelt", ru: "Окружающая среда" },
            { id: 7056, de: "das Klima", ru: "Климат" },
            { id: 7057, de: "scheinen", ru: "Светить" },
            { id: 7058, de: "regnen", ru: "Идет дождь" },
            { id: 7059, de: "schneien", ru: "Идет снег" },
            { id: 7060, de: "gewittern", ru: "Гроза" },
            { id: 7061, de: "bewölkt", ru: "Облачно" },
            { id: 7062, de: "neblig", ru: "Туманно" },
            { id: 7063, de: "trocken", ru: "Сухо" },
            { id: 7064, de: "nass", ru: "Мокро" },
            { id: 7065, de: "der Schatten", ru: "Тень" },
            { id: 7066, de: "die Hitze", ru: "Жара" },
            { id: 7067, de: "die Kälte", ru: "Холод" },
            { id: 7068, de: "der Grad", ru: "Градус" },
            { id: 7069, de: "steigen", ru: "Подниматься" },
            { id: 7070, de: "sinken", ru: "Опускаться" }
        ]
    },

    // --- ТЕМА 8: ЕДА ---
    "Еда": {
        simple: [
            { id: 8001, de: "essen", ru: "Есть" },
            { id: 8002, de: "trinken", ru: "Пить" },
            { id: 8003, de: "kochen", ru: "Готовить" },
            { id: 8004, de: "kaufen", ru: "Покупать" },
            { id: 8005, de: "das Essen", ru: "Еда" },
            { id: 8006, de: "das Getränk", ru: "Напиток" },
            { id: 8007, de: "das Brot", ru: "Хлеб" },
            { id: 8008, de: "das Wasser", ru: "Вода" },
            { id: 8009, de: "der Kaffee", ru: "Кофе" },
            { id: 8010, de: "der Tee", ru: "Чай" },
            { id: 8011, de: "die Milch", ru: "Молоко" },
            { id: 8012, de: "der Saft", ru: "Сок" },
            { id: 8013, de: "das Bier", ru: "Пиво" },
            { id: 8014, de: "der Wein", ru: "Вино" },
            { id: 8015, de: "das Ei", ru: "Яйцо" },
            { id: 8016, de: "der Käсе", ru: "Сыр" },
            { id: 8017, de: "das Fleisch", ru: "Мясо" },
            { id: 8018, de: "der Fisch", ru: "Рыба" },
            { id: 8019, de: "das Obst", ru: "Фрукты" },
            { id: 8020, de: "das Gemüse", ru: "Овощи" }
        ],
        hard: [
            { id: 8051, de: "die Ananas", ru: "Ананас" },
            { id: 8052, de: "der Pfirsich", ru: "Персик" },
            { id: 8053, de: "die Kirsche", ru: "Вишня" },
            { id: 8054, de: "die Erdbeere", ru: "Клубника" },
            { id: 8055, de: "die Himbeere", ru: "Малина" },
            { id: 8056, de: "die Weintraube", ru: "Виноград" },
            { id: 8057, de: "die Melone", ru: "Дыня" },
            { id: 8058, de: "die Wassermelone", ru: "Арбуз" },
            { id: 8059, de: "die Pflaume", ru: "Слива" },
            { id: 8060, de: "die Zitrone", ru: "Лимон" },
            { id: 8061, de: "die Banane", ru: "Банан" },
            { id: 8062, de: "der Apfel", ru: "Яблоко" },
            { id: 8063, de: "die Birne", ru: "Груша" },
            { id: 8064, de: "die Apfelsine", ru: "Апельсин" },
            { id: 8065, de: "die Kartoffel", ru: "Картофель" },
            { id: 8066, de: "die Tomate", ru: "Помидор" },
            { id: 8067, de: "die Gurke", ru: "Огурец" },
            { id: 8068, de: "der Zwiebel", ru: "Лук" },
            { id: 8069, de: "der Knoblauch", ru: "Чеснок" },
            { id: 8070, de: "die Karotte", ru: "Морковь" }
        ]
    }
};