const wordsRight = {
    "Люди и Семья": [
        { id: 30001, de: "der Mann", ru: "мужчина / муж" },
        { id: 30002, de: "die Frau", ru: "женщина / жена" },
        { id: 30003, de: "das Kind", ru: "ребёнок" },
        { id: 30004, de: "die Familie", ru: "семья" },
        { id: 30005, de: "der Freund", ru: "друг" },
        { id: 30006, de: "die Freundin", ru: "подруга" },
        { id: 30007, de: "der Vater", ru: "отец" },
        { id: 30008, de: "die Mutter", ru: "мать" },
        { id: 30009, de: "der Sohn", ru: "сын" },
        { id: 30010, de: "die Tochter", ru: "дочь" },
        { id: 30011, de: "der Bruder", ru: "брат" },
        { id: 30012, de: "die Schwester", ru: "сестра" },
        { id: 30013, de: "die Eltern", ru: "родители" },
        { id: 30014, de: "die Großeltern", ru: "дедушка и бабушка" },
        { id: 30015, de: "das Baby", ru: "младенец" },
        { id: 30016, de: "der Junge", ru: "мальчик" },
        { id: 30017, de: "das Mädchen", ru: "девочка" },
        { id: 30018, de: "der Nachbar", ru: "сосед" },
        { id: 30019, de: "die Leute", ru: "люди" },
        { id: 30020, de: "der Mensch", ru: "человек" },
        { id: 30021, de: "heißen", ru: "называться / зваться" },
        { id: 30022, de: "wohnen", ru: "проживать" },
        { id: 30023, de: "leben", ru: "жить" },
        { id: 30024, de: "kennen", ru: "знать (кого-то)" },
        { id: 30025, de: "lieben", ru: "любить" },
        { id: 30026, de: "helfen", ru: "помогать" },
        { id: 30027, de: "besuchen", ru: "посещать" },
        { id: 30028, de: "verstehen", ru: "понимать" },
        { id: 30029, de: "sprechen", ru: "говорить" },
        { id: 30030, de: "fragen", ru: "спрашивать" }
    ],
    "Дом и Жилье": [
        { id: 30101, de: "das Haus", ru: "дом" },
        { id: 30102, de: "die Wohnung", ru: "квартира" },
        { id: 30103, de: "das Zimmer", ru: "комната" },
        { id: 30104, de: "die Tür", ru: "дверь" },
        { id: 30105, de: "das Fenster", ru: "окно" },
        { id: 30106, de: "der Schlüssel", ru: "ключ" },
        { id: 30107, de: "der Tisch", ru: "стол" },
        { id: 30108, de: "der Stuhl", ru: "стул" },
        { id: 30109, de: "das Bett", ru: "кровать" },
        { id: 30110, de: "der Schrank", ru: "шкаф" },
        { id: 30111, de: "die Küche", ru: "кухня" },
        { id: 30112, de: "das Bad", ru: "ванная" },
        { id: 30113, de: "die Lampe", ru: "лампа" },
        { id: 30114, de: "das Bild", ru: "картина" },
        { id: 30115, de: "die Wand", ru: "стена" },
        { id: 30116, de: "der Boden", ru: "пол" },
        { id: 30117, de: "die Treppe", ru: "лестница" },
        { id: 30118, de: "der Balkon", ru: "балкон" },
        { id: 30119, de: "der Garten", ru: "сад" },
        { id: 30120, de: "die Miete", ru: "арендная плата" },
        { id: 30121, de: "öffnen", ru: "открывать" },
        { id: 30122, de: "schließen", ru: "закрывать" },
        { id: 30123, de: "putzen", ru: "чистить" },
        { id: 30124, de: "kochen", ru: "готовить еду" },
        { id: 30125, de: "schlafen", ru: "спать" },
        { id: 30126, de: "aufräumen", ru: "убираться" },
        { id: 30127, de: "waschen", ru: "мыть / стирать" },
        { id: 30128, de: "duschen", ru: "принимать душ" },
        { id: 30129, de: "mieten", ru: "арендовать" },
        { id: 30130, de: "umziehen", ru: "переезжать" }
    ],
    "Город и Ориентация": [
        { id: 30201, de: "die Stadt", ru: "город" },
        { id: 30202, de: "die Straße", ru: "улица" },
        { id: 30203, de: "der Platz", ru: "площадь" },
        { id: 30204, de: "das Zentrum", ru: "центр" },
        { id: 30205, de: "das Geschäft", ru: "магазин" },
        { id: 30206, de: "die Bank", ru: "банк" },
        { id: 30207, de: "das Hotel", ru: "отель" },
        { id: 30208, de: "die Kirche", ru: "церковь" },
        { id: 30209, de: "das Museum", ru: "музей" },
        { id: 30210, de: "der Park", ru: "парк" },
        { id: 30211, de: "der Bahnhof", ru: "вокзал" },
        { id: 30212, de: "die Haltestelle", ru: "остановка" },
        { id: 30213, de: "die Apotheke", ru: "аптека" },
        { id: 30214, de: "das Krankenhaus", ru: "больница" },
        { id: 30215, de: "die Post", ru: "почта" },
        { id: 30216, de: "die Karte", ru: "карта" },
        { id: 30217, de: "die Ecke", ru: "угол" },
        { id: 30218, de: "der Weg", ru: "путь / дорога" },
        { id: 30219, de: "die Ampel", ru: "светофор" },
        { id: 30220, de: "die Brücke", ru: "мост" },
        { id: 30221, de: "gehen", ru: "идти" },
        { id: 30222, de: "fahren", ru: "ехать" },
        { id: 30223, de: "finden", ru: "находить" },
        { id: 30224, de: "suchen", ru: "искать" },
        { id: 30225, de: "abbiegen", ru: "поворачивать" },
        { id: 30226, de: "warten", ru: "ждать" },
        { id: 30227, de: "ankommen", ru: "прибывать" },
        { id: 30228, de: "parken", ru: "парковаться" },
        { id: 30229, de: "zeigen", ru: "показывать" },
        { id: 30230, de: "besichtigen", ru: "осматривать" }
    ],
    "Еда и Кухня": [
        { id: 30301, de: "das Essen", ru: "еда" },
        { id: 30302, de: "das Getränk", ru: "напиток" },
        { id: 30303, de: "das Wasser", ru: "вода" },
        { id: 30304, de: "das Brot", ru: "хлеб" },
        { id: 30305, de: "die Milch", ru: "молоко" },
        { id: 30306, de: "der Kaffee", ru: "кофе" },
        { id: 30307, de: "der Tee", ru: "чай" },
        { id: 30308, de: "der Zucker", ru: "сахар" },
        { id: 30309, de: "das Salz", ru: "соль" },
        { id: 30310, de: "das Fleisch", ru: "мясо" },
        { id: 30311, de: "der Fisch", ru: "рыба" },
        { id: 30312, de: "das Gemüse", ru: "овощи" },
        { id: 30313, de: "das Obst", ru: "фрукты" },
        { id: 30314, de: "der Apfel", ru: "яблоко" },
        { id: 30315, de: "die Banane", ru: "банан" },
        { id: 30316, de: "das Ei", ru: "яйцо" },
        { id: 30317, de: "der Käse", ru: "сыр" },
        { id: 30318, de: "die Wurst", ru: "колбаса" },
        { id: 30319, de: "der Reis", ru: "рис" },
        { id: 30320, de: "die Suppe", ru: "суп" },
        { id: 30321, de: "essen", ru: "есть" },
        { id: 30322, de: "trinken", ru: "пить" },
        { id: 30323, de: "kochen", ru: "варить / готовить" },
        { id: 30324, de: "backen", ru: "печь" },
        { id: 30325, de: "bestellen", ru: "заказывать" },
        { id: 30326, de: "frühstücken", ru: "завтракать" },
        { id: 30327, de: "schmecken", ru: "пробовать / быть на вкус" },
        { id: 30328, de: "kaufen", ru: "покупать" },
        { id: 30329, de: "bezahlen", ru: "оплачивать" },
        { id: 30330, de: "schneiden", ru: "резать" }
    ],
    "Время и Даты": [
        { id: 30401, de: "die Zeit", ru: "время" },
        { id: 30402, de: "die Stunde", ru: "час" },
        { id: 30403, de: "die Minute", ru: "минута" },
        { id: 30404, de: "der Tag", ru: "день" },
        { id: 30405, de: "die Woche", ru: "неделя" },
        { id: 30406, de: "der Monat", ru: "месяц" },
        { id: 30407, de: "das Jahr", ru: "год" },
        { id: 30408, de: "der Morgen", ru: "утро" },
        { id: 30409, de: "der Mittag", ru: "полдень" },
        { id: 30410, de: "der Abend", ru: "вечер" },
        { id: 30411, de: "die Nacht", ru: "ночь" },
        { id: 30412, de: "der Montag", ru: "понедельник" },
        { id: 30413, de: "der Dienstag", ru: "вторник" },
        { id: 30414, de: "der Mittwoch", ru: "среда" },
        { id: 30415, de: "der Donnerstag", ru: "четверг" },
        { id: 30416, de: "der Freitag", ru: "пятница" },
        { id: 30417, de: "der Samstag", ru: "суббота" },
        { id: 30418, de: "der Sonntag", ru: "воскресенье" },
        { id: 30419, de: "das Datum", ru: "дата" },
        { id: 30420, de: "der Termin", ru: "встреча / срок" },
        { id: 30421, de: "beginnen", ru: "начинать" },
        { id: 30422, de: "enden", ru: "заканчивать" },
        { id: 30423, de: "dauern", ru: "длиться" },
        { id: 30424, de: "warten", ru: "ждать" },
        { id: 30425, de: "planen", ru: "планировать" },
        { id: 30426, de: "feiern", ru: "праздновать" },
        { id: 30427, de: "arbeiten", ru: "работать" },
        { id: 30428, de: "schlafen", ru: "спать" },
        { id: 30429, de: "kommen", ru: "приходить" },
        { id: 30430, de: "gehen", ru: "идти" }
    ],
    "Работа и Офис": [
        { id: 30501, de: "die Arbeit", ru: "работа" },
        { id: 30502, de: "der Beruf", ru: "профессия" },
        { id: 30503, de: "das Büro", ru: "офис" },
        { id: 30504, de: "der Kollege", ru: "коллега" },
        { id: 30505, de: "der Chef", ru: "начальник" },
        { id: 30506, de: "der Computer", ru: "компьютер" },
        { id: 30507, de: "das Telefon", ru: "телефон" },
        { id: 30508, de: "die E-Mail", ru: "электронная почта" },
        { id: 30509, de: "der Brief", ru: "письмо" },
        { id: 30510, de: "das Papier", ru: "бумага" },
        { id: 30511, de: "der Stift", ru: "ручка / карандаш" },
        { id: 30512, de: "das Projekt", ru: "проект" },
        { id: 30513, de: "die Pause", ru: "перерыв" },
        { id: 30514, de: "das Geld", ru: "деньги" },
        { id: 30515, de: "der Lohn", ru: "зарплата" },
        { id: 30516, de: "die Anzeige", ru: "объявление" },
        { id: 30517, de: "die Besprechung", ru: "совещание" },
        { id: 30518, de: "der Kunde", ru: "клиент" },
        { id: 30519, de: "das Formular", ru: "бланк / анкета" },
        { id: 30520, de: "der Vertrag", ru: "договор" },
        { id: 30521, de: "arbeiten", ru: "работать" },
        { id: 30522, de: "schreiben", ru: "писать" },
        { id: 30523, de: "lesen", ru: "читать" },
        { id: 30524, de: "telefonieren", ru: "говорить по телефону" },
        { id: 30525, de: "drucken", ru: "печатать" },
        { id: 30526, de: "organisieren", ru: "организовывать" },
        { id: 30527, de: "verdienen", ru: "зарабатывать" },
        { id: 30528, de: "helfen", ru: "помогать" },
        { id: 30529, de: "besuchen", ru: "посещать" },
        { id: 30530, de: "unterschreiben", ru: "подписывать" }
    ],
    "Природа и Погода": [
        { id: 30601, de: "die Natur", ru: "природа" },
        { id: 30602, de: "das Wetter", ru: "погода" },
        { id: 30603, de: "die Sonne", ru: "солнце" },
        { id: 30604, de: "der Mond", ru: "луна" },
        { id: 30605, de: "der Stern", ru: "звезда" },
        { id: 30606, de: "der Regen", ru: "дождь" },
        { id: 30607, de: "der Schnee", ru: "снег" },
        { id: 30608, de: "der Wind", ru: "ветер" },
        { id: 30609, de: "die Wolke", ru: "облако" },
        { id: 30610, de: "der Himmel", ru: "небо" },
        { id: 30611, de: "der Baum", ru: "дерево" },
        { id: 30612, de: "die Blume", ru: "цветок" },
        { id: 30613, de: "der Wald", ru: "лес" },
        { id: 30614, de: "der Berg", ru: "гора" },
        { id: 30615, de: "das Meer", ru: "море" },
        { id: 30616, de: "der See", ru: "озеро" },
        { id: 30617, de: "der Fluss", ru: "река" },
        { id: 30618, de: "das Tier", ru: "животное" },
        { id: 30619, de: "der Hund", ru: "собака" },
        { id: 30620, de: "die Katze", ru: "кошка" },
        { id: 30621, de: "scheinen", ru: "светить" },
        { id: 30622, de: "regnen", ru: "идти (о дожде)" },
        { id: 30623, de: "schneien", ru: "идти (о снеге)" },
        { id: 30624, de: "blühen", ru: "цвести" },
        { id: 30625, de: "wandern", ru: "ходить в поход" },
        { id: 30626, de: "schwimmen", ru: "плавать" },
        { id: 30627, de: "fliegen", ru: "летать" },
        { id: 30628, de: "laufen", ru: "бегать / идти" },
        { id: 30629, de: "sehen", ru: "видеть" },
        { id: 30630, de: "hören", ru: "слышать" }
    ],
    "Путешествия": [
        { id: 30701, de: "die Reise", ru: "путешествие" },
        { id: 30702, de: "der Urlaub", ru: "отпуск" },
        { id: 30703, de: "das Ziel", ru: "цель / пункт назначения" },
        { id: 30704, de: "das Auto", ru: "автомобиль" },
        { id: 30705, de: "der Zug", ru: "поезд" },
        { id: 30706, de: "das Flugzeug", ru: "самолёт" },
        { id: 30707, de: "der Bus", ru: "автобус" },
        { id: 30708, de: "das Fahrrad", ru: "велосипед" },
        { id: 30709, de: "das Ticket", ru: "билет" },
        { id: 30710, de: "der Pass", ru: "паспорт" },
        { id: 30711, de: "der Koffer", ru: "чемодан" },
        { id: 30712, de: "die Tasche", ru: "сумка" },
        { id: 30713, de: "das Hotel", ru: "отель" },
        { id: 30714, de: "die Grenze", ru: "граница" },
        { id: 30715, de: "der Flughafen", ru: "аэропорт" },
        { id: 30716, de: "der Bahnhof", ru: "вокзал" },
        { id: 30717, de: "das Ausland", ru: "заграница" },
        { id: 30718, de: "die Stadt", ru: "город" },
        { id: 30719, de: "das Land", ru: "страна" },
        { id: 30720, de: "der Strand", ru: "пляж" },
        { id: 30721, de: "reisen", ru: "путешествовать" },
        { id: 30722, de: "fliegen", ru: "летать" },
        { id: 30723, de: "fahren", ru: "ехать" },
        { id: 30724, de: "packen", ru: "паковать" },
        { id: 30725, de: "buchen", ru: "бронировать" },
        { id: 30726, de: "besuchen", ru: "посещать" },
        { id: 30727, de: "sehen", ru: "видеть" },
        { id: 30728, de: "fotografieren", ru: "фотографировать" },
        { id: 30729, de: "warten", ru: "ждать" },
        { id: 30730, de: "ankommen", ru: "прибывать" }
    ]
};