const wordsLeft = {
    "Базовые Глаголы": [
        { id: 20001, de: "sein", ru: "быть" },
        { id: 20002, de: "haben", ru: "иметь" },
        { id: 20003, de: "werden", ru: "становиться" },
        { id: 20004, de: "können", ru: "мочь / уметь" },
        { id: 20005, de: "müssen", ru: "быть должным (объективно)" },
        { id: 20006, de: "sagen", ru: "говорить / сказать" },
        { id: 20007, de: "machen", ru: "делать" },
        { id: 20008, de: "geben", ru: "давать" },
        { id: 20009, de: "kommen", ru: "приходить / приезжать" },
        { id: 20010, de: "sollen", ru: "следовать / быть должным" },
        { id: 20011, de: "wollen", ru: "хотеть" },
        { id: 20012, de: "gehen", ru: "идти" },
        { id: 20013, de: "wissen", ru: "знать (факт)" },
        { id: 20014, de: "sehen", ru: "видеть" },
        { id: 20015, de: "lassen", ru: "позволять / оставлять" },
        { id: 20016, de: "stehen", ru: "стоять" },
        { id: 20017, de: "finden", ru: "находить" },
        { id: 20018, de: "bleiben", ru: "оставаться" },
        { id: 20019, de: "liegen", ru: "лежать" },
        { id: 20020, de: "heißen", ru: "называться" },
        { id: 20021, de: "denken", ru: "думать" },
        { id: 20022, de: "nehmen", ru: "брать" },
        { id: 20023, de: "tun", ru: "делать / исполнять" },
        { id: 20024, de: "dürfen", ru: "иметь разрешение" },
        { id: 20025, de: "glauben", ru: "верить / полагать" },
        { id: 20026, de: "halten", ru: "держать / останавливаться" },
        { id: 20027, de: "nennen", ru: "называть" },
        { id: 20028, de: "mögen", ru: "нравиться" },
        { id: 20029, de: "zeigen", ru: "показывать" },
        { id: 20030, de: "führen", ru: "вести / руководить" }
    ],
    "Местоимения": [
        { id: 20101, de: "ich", ru: "я" },
        { id: 20102, de: "du", ru: "ты" },
        { id: 20103, de: "er", ru: "он" },
        { id: 20104, de: "sie", ru: "она / они" },
        { id: 20105, de: "es", ru: "оно" },
        { id: 20106, de: "wir", ru: "мы" },
        { id: 20107, de: "ihr", ru: "вы (мн. число)" },
        { id: 20108, de: "Sie", ru: "Вы (вежливо)" },
        { id: 20109, de: "mein", ru: "мой" },
        { id: 20110, de: "dein", ru: "твой" },
        { id: 20111, de: "sein", ru: "его" },
        { id: 20112, de: "ihr", ru: "её / их" },
        { id: 20113, de: "unser", ru: "наш" },
        { id: 20114, de: "euer", ru: "ваш (мн.ч.)" },
        { id: 20115, de: "dieser", ru: "этот" },
        { id: 20116, de: "jener", ru: "тот" },
        { id: 20117, de: "man", ru: "неопределенно-личное" },
        { id: 20118, de: "jemand", ru: "кто-то" },
        { id: 20119, de: "niemand", ru: "никто" },
        { id: 20120, de: "etwas", ru: "что-то" },
        { id: 20121, de: "nichts", ru: "ничего" },
        { id: 20122, de: "alle", ru: "все" },
        { id: 20123, de: "jeder", ru: "каждый" },
        { id: 20124, de: "mancher", ru: "некоторый" },
        { id: 20125, de: "mich", ru: "меня" },
        { id: 20126, de: "dich", ru: "тебя" },
        { id: 20127, de: "uns", ru: "нас" },
        { id: 20128, de: "euch", ru: "вас" },
        { id: 20129, de: "mir", ru: "мне" },
        { id: 20130, de: "dir", ru: "тебе" }
    ],
    "Прилагательные": [
        { id: 20201, de: "gut", ru: "хороший" },
        { id: 20202, de: "schlecht", ru: "плохой" },
        { id: 20203, de: "groß", ru: "большой" },
        { id: 20204, de: "klein", ru: "маленький" },
        { id: 20205, de: "neu", ru: "новый" },
        { id: 20206, de: "alt", ru: "старый" },
        { id: 20207, de: "schön", ru: "красивый" },
        { id: 20208, de: "hässlich", ru: "некрасивый" },
        { id: 20209, de: "teuer", ru: "дорогой" },
        { id: 20210, de: "billig", ru: "дешевый" },
        { id: 20211, de: "schnell", ru: "быстрый" },
        { id: 20212, de: "langsam", ru: "медленный" },
        { id: 20213, de: "hell", ru: "светлый" },
        { id: 20214, de: "dunkel", ru: "темный" },
        { id: 20215, de: "laut", ru: "громкий" },
        { id: 20216, de: "leise", ru: "тихий" },
        { id: 20217, de: "schwer", ru: "тяжелый / трудный" },
        { id: 20218, de: "leicht", ru: "легкий" },
        { id: 20219, de: "richtig", ru: "правильный" },
        { id: 20220, de: "falsch", ru: "неправильный" },
        { id: 20221, de: "kalt", ru: "холодный" },
        { id: 20222, de: "warm", ru: "теплый" },
        { id: 20223, de: "jung", ru: "молодой" },
        { id: 20224, de: "klug", ru: "умный" },
        { id: 20225, de: "müde", ru: "усталый" },
        { id: 20226, de: "lustig", ru: "веселый" },
        { id: 20227, de: "traurig", ru: "грустный" },
        { id: 20228, de: "sauber", ru: "чистый" },
        { id: 20229, de: "schmutzig", ru: "грязный" },
        { id: 20230, de: "wichtig", ru: "важный" }
    ],
    "Вопросы": [
        { id: 20301, de: "wer", ru: "кто" },
        { id: 20302, de: "was", ru: "что" },
        { id: 20303, de: "wie", ru: "как" },
        { id: 20304, de: "wo", ru: "где" },
        { id: 20305, de: "woher", ru: "откуда" },
        { id: 20306, de: "wohin", ru: "куда" },
        { id: 20307, de: "wann", ru: "когда" },
        { id: 20308, de: "warum", ru: "почему" },
        { id: 20309, de: "welcher", ru: "какой" },
        { id: 20310, de: "wieviel", ru: "сколько" },
        { id: 20311, de: "wie lange", ru: "как долго" },
        { id: 20312, de: "wie oft", ru: "как часто" },
        { id: 20313, de: "weshalb", ru: "зачем / почему" },
        { id: 20314, de: "wessen", ru: "чей" },
        { id: 20315, de: "mit wem", ru: "с кем" },
        { id: 20316, de: "von wem", ru: "от кого" },
        { id: 20317, de: "um wie viel Uhr", ru: "в котором часу" },
        { id: 20318, de: "seit wann", ru: "с каких пор" },
        { id: 20319, de: "bis wann", ru: "до каких пор" },
        { id: 20320, de: "was für ein", ru: "что за / какой именно" },
        { id: 20321, de: "wie alt", ru: "сколько лет" },
        { id: 20322, de: "wie groß", ru: "какого роста" },
        { id: 20323, de: "wie weit", ru: "как далеко" },
        { id: 20324, de: "wozu", ru: "для чего" },
        { id: 20325, de: "worüber", ru: "о чем" },
        { id: 20326, de: "womit", ru: "чем" },
        { id: 20327, de: "woran", ru: "о чем / на чем" },
        { id: 20328, de: "woraus", ru: "из чего" },
        { id: 20329, de: "wodurch", ru: "как / за счет чего" },
        { id: 20330, de: "wovon", ru: "о чем / от чего" }
    ],
    "Обстоятельства": [
        { id: 20801, de: "hier", ru: "здесь" },
        { id: 20802, de: "dort", ru: "там" },
        { id: 20803, de: "links", ru: "слева" },
        { id: 20804, de: "rechts", ru: "справа" },
        { id: 20805, de: "oben", ru: "вверху" },
        { id: 20806, de: "unten", ru: "внизу" },
        { id: 20807, de: "vorn", ru: "спереди" },
        { id: 20808, de: "hinten", ru: "сзади" },
        { id: 20809, de: "überall", ru: "повсюду" },
        { id: 20810, de: "draußen", ru: "снаружи" },
        { id: 20811, de: "drinnen", ru: "внутри" },
        { id: 20812, de: "heute", ru: "сегодня" },
        { id: 20813, de: "morgen", ru: "завтра" },
        { id: 20814, de: "gestern", ru: "вчера" },
        { id: 20815, de: "jetzt", ru: "сейчас" },
        { id: 20816, de: "immer", ru: "всегда" },
        { id: 20817, de: "oft", ru: "часто" },
        { id: 20818, de: "manchmal", ru: "иногда" },
        { id: 20819, de: "selten", ru: "редко" },
        { id: 20820, de: "nie", ru: "никогда" },
        { id: 20821, de: "bald", ru: "скоро" },
        { id: 20822, de: "sofort", ru: "немедленно" },
        { id: 20823, de: "zuerst", ru: "сначала" },
        { id: 20824, de: "dann", ru: "потом" },
        { id: 20825, de: "gern", ru: "охотно" },
        { id: 20826, de: "vielleicht", ru: "возможно" },
        { id: 20827, de: "wirklich", ru: "действительно" },
        { id: 20828, de: "zusammen", ru: "вместе" },
        { id: 20829, de: "allein", ru: "один" },
        { id: 20830, de: "genug", ru: "достаточно" }
    ]
};