const wordCollections = {
    // --- ТЕМА 1: КТО Я / СЕМЬЯ ---
    "Кто я?": {
        simple: [
            { id: 1001, de: "ich", ru: "Я" },
            { id: 1002, de: "du", ru: "Ты" },
            { id: 1003, de: "der Name", ru: "Имя" },
            { id: 1004, de: "die Familie", ru: "Семья" },
            { id: 1005, de: "der Vater", ru: "Папа" },
            { id: 1006, de: "die Mutter", ru: "Мама" },
            { id: 1007, de: "der Bruder", ru: "Брат" },
            { id: 1008, de: "die Schwester", ru: "Сестра" },
            { id: 1009, de: "das Kind", ru: "Ребенок" },
            { id: 1010, de: "der Sohn", ru: "Сын" },
            { id: 1011, de: "die Tochter", ru: "Дочь" },
            { id: 1012, de: "der Mann", ru: "Мужчина / Муж" },
            { id: 1013, de: "die Frau", ru: "Женщина / Жена" },
            { id: 1014, de: "der Junge", ru: "Мальчик" },
            { id: 1015, de: "das Mädchen", ru: "Девочка" },
            { id: 1016, de: "wohnen", ru: "Жить (проживать)" },
            { id: 1017, de: "kommen", ru: "Приходить / Быть родом из" },
            { id: 1018, de: "alt", ru: "Старый" },
            { id: 1019, de: "jung", ru: "Молодой" },
            { id: 1020, de: "der Freund", ru: "Друг" }
        ],
        hard: [
            { id: 1051, de: "der Vorname", ru: "Имя (собственное)" },
            { id: 1052, de: "der Nachname", ru: "Фамилия" },
            { id: 1053, de: "das Alter", ru: "Возраст" },
            { id: 1054, de: "der Geburtstag", ru: "День рождения" },
            { id: 1055, de: "geboren", ru: "Рожденный" },
            { id: 1056, de: "ledig", ru: "Холост / Незамужем" },
            { id: 1057, de: "verheiratet", ru: "Женат / Замужем" },
            { id: 1058, de: "geschieden", ru: "Разведен(а)" },
            { id: 1059, de: "die Adresse", ru: "Адрес" },
            { id: 1060, de: "die Straße", ru: "Улица" },
            { id: 1061, de: "die Hausnummer", ru: "Номер дома" },
            { id: 1062, de: "die Stadt", ru: "Город" },
            { id: 1063, de: "das Land", ru: "Страна" },
            { id: 1064, de: "die Sprache", ru: "Язык" },
            { id: 1065, de: "berufstätig", ru: "Работающий" },
            { id: 1066, de: "der Verwandte", ru: "Родственник" },
            { id: 1067, de: "die Großeltern", ru: "Бабушка и дедушка" },
            { id: 1068, de: "der Enkel", ru: "Внук" },
            { id: 1069, de: "die Tante", ru: "Тетя" },
            { id: 1070, de: "der Onkel", ru: "Дядя" }
        ]
    },

    // --- ТЕМА 2: ЦИФРЫ ---
    "Цифры": {
        simple: [
            { id: 2001, de: "null", ru: "Ноль" },
            { id: 2002, de: "eins", ru: "Один" },
            { id: 2003, de: "zwei", ru: "Два" },
            { id: 2004, de: "drei", ru: "Три" },
            { id: 2005, de: "vier", ru: "Четыре" },
            { id: 2006, de: "fünf", ru: "Пять" },
            { id: 2007, de: "sechs", ru: "Шесть" },
            { id: 2008, de: "sieben", ru: "Семь" },
            { id: 2009, de: "acht", ru: "Восемь" },
            { id: 2010, de: "neun", ru: "Девять" },
            { id: 2011, de: "zehn", ru: "Десять" },
            { id: 2012, de: "elf", ru: "Одиннадцать" },
            { id: 2013, de: "zwölf", ru: "Двенадцать" },
            { id: 2014, de: "zwanzig", ru: "Двадцать" },
            { id: 2015, de: "dreißig", ru: "Тридцать" },
            { id: 2016, de: "vierzig", ru: "Сорок" },
            { id: 2017, de: "fünfzig", ru: "Пятьдесят" },
            { id: 2018, de: "hundert", ru: "Сто" },
            { id: 2019, de: "tausend", ru: "Тысяча" },
            { id: 2020, de: "die Nummer", ru: "Номер" }
        ],
        hard: [
            { id: 2051, de: "erste", ru: "Первый" },
            { id: 2052, de: "zweite", ru: "Второй" },
            { id: 2053, de: "dritte", ru: "Третий" },
            { id: 2054, de: "letzte", ru: "Последний" },
            { id: 2055, de: "nächste", ru: "Следующий" },
            { id: 2056, de: "einmal", ru: "Один раз" },
            { id: 2057, de: "zweimal", ru: "Дважды" },
            { id: 2058, de: "die Hälfte", ru: "Половина" },
            { id: 2059, de: "das Drittel", ru: "Треть" },
            { id: 2060, de: "das Viertel", ru: "Четверть" },
            { id: 2061, de: "beide", ru: "Оба" },
            { id: 2062, de: "wenig", ru: "Мало" },
            { id: 2063, de: "viel", ru: "Много" },
            { id: 2064, de: "mehr", ru: "Больше" },
            { id: 2065, de: "weniger", ru: "Меньше" },
            { id: 2066, de: "die Million", ru: "Миллион" },
            { id: 2067, de: "rechnen", ru: "Считать" },
            { id: 2068, de: "zählen", ru: "Подсчитывать" },
            { id: 2069, de: "das Ergebnis", ru: "Результат" },
            { id: 2070, de: "die Zahl", ru: "Число" }
        ]
    },

    // --- ТЕМА 3: ЦВЕТА ---
    "Цвета": {
        simple: [
            { id: 3001, de: "die Farbe", ru: "Цвет" },
            { id: 3002, de: "rot", ru: "Красный" },
            { id: 3003, de: "blau", ru: "Синий" },
            { id: 3004, de: "grün", ru: "Зеленый" },
            { id: 3005, de: "gelb", ru: "Желтый" },
            { id: 3006, de: "schwarz", ru: "Черный" },
            { id: 3007, de: "weiß", ru: "Белый" },
            { id: 3008, de: "grau", ru: "Серый" },
            { id: 3009, de: "braun", ru: "Коричневый" },
            { id: 3010, de: "orange", ru: "Оранжевый" },
            { id: 3011, de: "rosa", ru: "Розовый" },
            { id: 3012, de: "lila", ru: "Лиловый" },
            { id: 3013, de: "hell", ru: "Светлый" },
            { id: 3014, de: "dunkel", ru: "Темный" },
            { id: 3015, de: "bunt", ru: "Пестрый / Разноцветный" },
            { id: 3016, de: "golden", ru: "Золотой" },
            { id: 3017, de: "silbern", ru: "Серебряный" },
            { id: 3018, de: "klar", ru: "Прозрачный / Ясный" },
            { id: 3019, de: "schön", ru: "Красивый" },
            { id: 3020, de: "hässlich", ru: "Некрасивый" }
        ],
        hard: [
            { id: 3051, de: "hellblau", ru: "Голубой" },
            { id: 3052, de: "dunkelrot", ru: "Темно-красный" },
            { id: 3053, de: "türkis", ru: "Бирюзовый" },
            { id: 3054, de: "violett", ru: "Фиолетовый" },
            { id: 3055, de: "beige", ru: "Бежевый" },
            { id: 3056, de: "cremefarben", ru: "Кремовый" },
            { id: 3057, de: "blass", ru: "Бледный" },
            { id: 3058, de: "leuchtend", ru: "Светящийся / Яркий" },
            { id: 3059, de: "unsichtbar", ru: "Невидимый" },
            { id: 3060, de: "kariert", ru: "В клетку" },
            { id: 3061, de: "gestreift", ru: "В полоску" },
            { id: 3062, de: "gepunktet", ru: "В горошек" },
            { id: 3063, de: "einfarbig", ru: "Однотонный" },
            { id: 3064, de: "malen", ru: "Рисовать (красками)" },
            { id: 3065, de: "zeichnen", ru: "Рисовать (карандашом)" },
            { id: 3066, de: "das Bild", ru: "Картина" },
            { id: 3067, de: "aussehen", ru: "Выглядеть" },
            { id: 3068, de: "ähnlich", ru: "Похожий" },
            { id: 3069, de: "verschieden", ru: "Различный" },
            { id: 3070, de: "gleich", ru: "Одинаковый" }
        ]
    },

    // --- ТЕМА 4: ПРОФЕССИИ ---
    "Профессии": {
        simple: [
            { id: 4001, de: "der Beruf", ru: "Профессия" },
            { id: 4002, de: "die Arbeit", ru: "Работа" },
            { id: 4003, de: "arbeiten", ru: "Работать" },
            { id: 4004, de: "der Lehrer", ru: "Учитель" },
            { id: 4005, de: "der Arzt", ru: "Врач" },
            { id: 4006, de: "der Schüler", ru: "Ученик" },
            { id: 4007, de: "der Student", ru: "Студент" },
            { id: 4008, de: "der Fahrer", ru: "Водитель" },
            { id: 4009, de: "der Verkäufer", ru: "Продавец" },
            { id: 4010, de: "der Koch", ru: "Повар" },
            { id: 4011, de: "der Kellner", ru: "Официант" },
            { id: 4012, de: "der Polizist", ru: "Полицейский" },
            { id: 4013, de: "der Bäcker", ru: "Пекарь" },
            { id: 4014, de: "der Friseur", ru: "Парикмахер" },
            { id: 4015, de: "der Sänger", ru: "Певец" },
            { id: 4016, de: "der Chef", ru: "Шеф / Начальник" },
            { id: 4017, de: "der Kollege", ru: "Коллега" },
            { id: 4018, de: "das Büro", ru: "Офис" },
            { id: 4019, de: "die Schule", ru: "Школа" },
            { id: 4020, de: "das Geld", ru: "Деньги" }
        ],
        hard: [
            { id: 4051, de: "der Ingenieur", ru: "Инженер" },
            { id: 4052, de: "der Anwalt", ru: "Адвокат" },
            { id: 4053, de: "der Architekt", ru: "Архитектор" },
            { id: 4054, de: "der Journalist", ru: "Журналист" },
            { id: 4055, de: "der Schauspieler", ru: "Актер" },
            { id: 4056, de: "die Krankenschwester", ru: "Медсестра" },
            { id: 4057, de: "der Sekretär", ru: "Секретарь" },
            { id: 4058, de: "der Handwerker", ru: "Ремесленник / Мастер" },
            { id: 4059, de: "der Mechaniker", ru: "Механик" },
            { id: 4060, de: "der Feuerwehrmann", ru: "Пожарный" },
            { id: 4061, de: "der Bauer", ru: "Фермер" },
            { id: 4062, de: "der Programmierer", ru: "Программист" },
            { id: 4063, de: "der Zahnarzt", ru: "Стоматолог" },
            { id: 4064, de: "der Tierarzt", ru: "Ветеринар" },
            { id: 4065, de: "der Richter", ru: "Судья" },
            { id: 4066, de: "der Wissenschaftler", ru: "Ученый" },
            { id: 4067, de: "arbeitslos", ru: "Безработный" },
            { id: 4068, de: "verdienen", ru: "Зарабатывать" },
            { id: 4069, de: "die Firma", ru: "Фирма" },
            { id: 4070, de: "der Feierabend", ru: "Конец рабочего дня" }
        ]
    },

    // --- ТЕМА 5: ГЛАГОЛЫ A1 ---
    "Глаголы А1": {
        simple: [
            { id: 5001, de: "sein", ru: "Быть" },
            { id: 5002, de: "haben", ru: "Иметь" },
            { id: 5003, de: "machen", ru: "Делать" },
            { id: 5004, de: "gehen", ru: "Идти" },
            { id: 5005, de: "kommen", ru: "Приходить" },
            { id: 5006, de: "lernen", ru: "Учиться" },
            { id: 5007, de: "essen", ru: "Есть (кушать)" },
            { id: 5008, de: "trinken", ru: "Пить" },
            { id: 5009, de: "schlafen", ru: "Спать" },
            { id: 5010, de: "spielen", ru: "Играть" },
            { id: 5011, de: "schreiben", ru: "Писать" },
            { id: 5012, de: "lesen", ru: "Читать" },
            { id: 5013, de: "hören", ru: "Слушать" },
            { id: 5014, de: "sprechen", ru: "Говорить" },
            { id: 5015, de: "wohnen", ru: "Жить" },
            { id: 5016, de: "arbeiten", ru: "Работать" },
            { id: 5017, de: "kaufen", ru: "Покупать" },
            { id: 5018, de: "sehen", ru: "Видеть" },
            { id: 5019, de: "fragen", ru: "Спрашивать" },
            { id: 5020, de: "antworten", ru: "Отвечать" }
        ],
        hard: [
            { id: 5051, de: "aufstehen", ru: "Вставать" },
            { id: 5052, de: "fernsehen", ru: "Смотреть ТВ" },
            { id: 5053, de: "einkaufen", ru: "Делать покупки" },
            { id: 5054, de: "anrufen", ru: "Звонить" },
            { id: 5055, de: "frühstücken", ru: "Завтракать" },
            { id: 5056, de: "verstehen", ru: "Понимать" },
            { id: 5057, de: "besuchen", ru: "Посещать" },
            { id: 5058, de: "bezahlen", ru: "Оплачивать" },
            { id: 5059, de: "bestellen", ru: "Заказывать" },
            { id: 5060, de: "brauchen", ru: "Нуждаться" },
            { id: 5061, de: "suchen", ru: "Искать" },
            { id: 5062, de: "finden", ru: "Находить" },
            { id: 5063, de: "kosten", ru: "Стоить" },
            { id: 5064, de: "reisen", ru: "Путешествовать" },
            { id: 5065, de: "warten", ru: "Ждать" },
            { id: 5066, de: "öffnen", ru: "Открывать" },
            { id: 5067, de: "schließen", ru: "Закрывать" },
            { id: 5068, de: "sagen", ru: "Сказать" },
            { id: 5069, de: "lieben", ru: "Любить" },
            { id: 5070, de: "lachen", ru: "Смеяться" }
        ]
    },

    // --- ТЕМА 6: ГЛАГОЛЫ A2 ---
    "Глаголы А2": {
        simple: [
            { id: 6001, de: "erklären", ru: "Объяснять" },
            { id: 6002, de: "erzählen", ru: "Рассказывать" },
            { id: 6003, de: "verkaufen", ru: "Продавать" },
            { id: 6004, de: "vergessen", ru: "Забывать" },
            { id: 6005, de: "verlieren", ru: "Терять" },
            { id: 6006, de: "gewinnen", ru: "Выигрывать" },
            { id: 6007, de: "anfangen", ru: "Начинать" },
            { id: 6008, de: "aufhören", ru: "Прекращать" },
            { id: 6009, de: "einladen", ru: "Приглашать" },
            { id: 6010, de: "gratulieren", ru: "Поздравлять" },
            { id: 6011, de: "helfen", ru: "Помогать" },
            { id: 6012, de: "danken", ru: "Благодарить" },
            { id: 6013, de: "gefallen", ru: "Нравиться" },
            { id: 6014, de: "gehören", ru: "Принадлежать" },
            { id: 6015, de: "passieren", ru: "Случаться" },
            { id: 6016, de: "treffen", ru: "Встречать" },
            { id: 6017, de: "mitbringen", ru: "Приносить с собой" },
            { id: 6018, de: "abholen", ru: "Забирать / Встречать" },
            { id: 6019, de: "umsteigen", ru: "Пересаживаться" },
            { id: 6020, de: "einsteigen", ru: "Садиться (в транспорт)" }
        ],
        hard: [
            { id: 6051, de: "sich freuen", ru: "Радоваться" },
            { id: 6052, de: "sich ärgern", ru: "Злиться" },
            { id: 6053, de: "sich interessieren", ru: "Интересоваться" },
            { id: 6054, de: "teilnehmen", ru: "Участвовать" },
            { id: 6055, de: "stattfinden", ru: "Состояться" },
            { id: 6056, de: "vereinbaren", ru: "Договариваться" },
            { id: 6057, de: "verschieben", ru: "Переносить (срок)" },
            { id: 6058, de: "absagen", ru: "Отменять" },
            { id: 6059, de: "diskutieren", ru: "Обсуждать" },
            { id: 6060, de: "übernachten", ru: "Ночевать" },
            { id: 6061, de: "besichtigen", ru: "Осматривать" },
            { id: 6062, de: "reparieren", ru: "Ремонтировать" },
            { id: 6063, de: "funktionieren", ru: "Функционировать" },
            { id: 6064, de: "benutzen", ru: "Использовать" },
            { id: 6065, de: "übersetzen", ru: "Переводить" },
            { id: 6066, de: "wiederholen", ru: "Повторять" },
            { id: 6067, de: "vorbereiten", ru: "Подготавливать" },
            { id: 6068, de: "unterschreiben", ru: "Подписывать" },
            { id: 6069, de: "verdienen", ru: "Заслуживать / Зарабатывать" },
            { id: 6070, de: "empfehlen", ru: "Рекомендовать" }
        ]
    },

    // --- ТЕМА 7: МЕСТОИМЕНИЯ ---
    "Местоимения": {
        simple: [
            { id: 7001, de: "ich", ru: "Я" },
            { id: 7002, de: "du", ru: "Ты" },
            { id: 7003, de: "er", ru: "Он" },
            { id: 7004, de: "sie", ru: "Она" },
            { id: 7005, de: "es", ru: "Оно" },
            { id: 7006, de: "wir", ru: "Мы" },
            { id: 7007, de: "ihr", ru: "Вы (друзьям)" },
            { id: 7008, de: "Sie", ru: "Вы (вежливо)" },
            { id: 7009, de: "sie (Pl)", ru: "Они" },
            { id: 7010, de: "mein", ru: "Мой" },
            { id: 7011, de: "dein", ru: "Твой" },
            { id: 7012, de: "sein", ru: "Его" },
            { id: 7013, de: "ihr", ru: "Её / Их" },
            { id: 7014, de: "unser", ru: "Наш" },
            { id: 7015, de: "euer", ru: "Ваш" },
            { id: 7016, de: "wer", ru: "Кто" },
            { id: 7017, de: "was", ru: "Что" },
            { id: 7018, de: "wo", ru: "Где" },
            { id: 7019, de: "wann", ru: "Когда" },
            { id: 7020, de: "wie", ru: "Как" }
        ],
        hard: [
            { id: 7051, de: "mich", ru: "Меня" },
            { id: 7052, de: "dich", ru: "Тебя" },
            { id: 7053, de: "ihn", ru: "Его (вин. падеж)" },
            { id: 7054, de: "uns", ru: "Нас" },
            { id: 7055, de: "euch", ru: "Вас" },
            { id: 7056, de: "mir", ru: "Мне" },
            { id: 7057, de: "dir", ru: "Тебе" },
            { id: 7058, de: "ihm", ru: "Ему" },
            { id: 7059, de: "ihr (Dativ)", ru: "Ей (дат. падеж)" },
            { id: 7060, de: "Ihnen", ru: "Вам" },
            { id: 7061, de: "dieser", ru: "Этот" },
            { id: 7062, de: "jener", ru: "Тот" },
            { id: 7063, de: "welcher", ru: "Который" },
            { id: 7064, de: "jeder", ru: "Каждый" },
            { id: 7065, de: "manche", ru: "Некоторые" },
            { id: 7066, de: "alle", ru: "Все" },
            { id: 7067, de: "niemand", ru: "Никто" },
            { id: 7068, de: "jemand", ru: "Кто-то" },
            { id: 7069, de: "etwas", ru: "Что-то" },
            { id: 7070, de: "nichts", ru: "Ничего" }
        ]
    },

    // --- ТЕМА 8: ФРУКТЫ-ОВОЩИ ---
    "Фрукты-Овощи": {
        simple: [
            { id: 8001, de: "der Apfel", ru: "Яблоко" },
            { id: 8002, de: "die Banane", ru: "Банан" },
            { id: 8003, de: "die Orange", ru: "Апельсин" },
            { id: 8004, de: "die Zitrone", ru: "Лимон" },
            { id: 8005, de: "die Birne", ru: "Груша" },
            { id: 8006, de: "die Kartoffel", ru: "Картошка" },
            { id: 8007, de: "die Tomate", ru: "Помидор" },
            { id: 8008, de: "die Gurke", ru: "Огурец" },
            { id: 8009, de: "die Zwiebel", ru: "Лук" },
            { id: 8010, de: "die Karotte", ru: "Морковь" },
            { id: 8011, de: "das Brot", ru: "Хлеб" },
            { id: 8012, de: "das Wasser", ru: "Вода" },
            { id: 8013, de: "die Milch", ru: "Молоко" },
            { id: 8014, de: "der Saft", ru: "Сок" },
            { id: 8015, de: "das Ei", ru: "Яйцо" },
            { id: 8016, de: "der Käse", ru: "Сыр" },
            { id: 8017, de: "das Fleisch", ru: "Мясо" },
            { id: 8018, de: "der Fisch", ru: "Рыба" },
            { id: 8019, de: "das Obst", ru: "Фрукты" },
            { id: 8020, de: "das Gemüse", ru: "Овощи" }
        ],
        hard: [
            { id: 8051, de: "die Ananas", ru: "Ананас" },
            { id: 8052, de: "der Pfirsich", ru: "Персик" },
            { id: 8053, de: "die Kirsche", ru: "Вишня" },
            { id: 8054, de: "die Erdbeere", ru: "Клубника" },
            { id: 8055, de: "die Himbeere", ru: "Малина" },
            { id: 8056, de: "die Weintraube", ru: "Виноград" },
            { id: 8057, de: "die Melone", ru: "Дыня" },
            { id: 8058, de: "die Wassermelone", ru: "Арбуз" },
            { id: 8059, de: "die Pflaume", ru: "Слива" },
            { id: 8060, de: "die Aprikose", ru: "Абрикос" },
            { id: 8061, de: "die Paprika", ru: "Болгарский перец" },
            { id: 8062, de: "der Salat", ru: "Салат" },
            { id: 8063, de: "der Kohl", ru: "Капуста" },
            { id: 8064, de: "der Knoblauch", ru: "Чеснок" },
            { id: 8065, de: "der Pilz", ru: "Гриб" },
            { id: 8066, de: "der Kürbis", ru: "Тыква" },
            { id: 8067, de: "die Erbse", ru: "Горох" },
            { id: 8068, de: "die Bohne", ru: "Фасоль" },
            { id: 8069, de: "der Mais", ru: "Кукуруза" },
            { id: 8070, de: "die Nuss", ru: "Орех" }
        ]
    }
};